name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.2

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  envied_flutter: ^0.3.0+1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  in_app_review: ^2.0.6
  injectable: ^2.3.0
  intl:
  json_annotation: ^4.8.1
  purchases_flutter: ^5.6.4
  recase: ^4.1.0
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  envied_flutter_generator: ^0.3.0
  # flutter_test:
  #   sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  # assets:

scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  get: "rm -rf pubspec.lock && flutter pub get"
  gen: dart run build_runner watch --delete-conflicting-outputs
  clean:
    ios: cd ios && rm -rf Podfile.lock Pods/ && pod install --repo-update && cd ../
    runner: dart run build_runner clean
  firebase:
    run-emulators: "firebase emulators:start --import firebase_emulators_export"
    save: "firebase emulators:export firebase_emulator_exports"
    kill-port: lsof -ti tcp:8080 | xargs kill -9
